apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Zentrale Basisdomain für alle externen Webadressen. Bei einem Wechsel nur
# den folgenden Wert ändern.
configMapGenerator:
  - name: skip-cluster-settings
    literals:
      - SKIP_BASE_DOMAIN=192-168-0-166.sslip.io

generatorOptions:
  disableNameSuffixHash: true
