apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd
  namespace: argocd
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`argocd.192-168-0-166.sslip.io`)
      services:
        - name: argocd-server
          port: 80
  tls: {}
