apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../cluster-host
  - configmap.yaml
  - ingressroute.yaml

replacements:
  - source:
      kind: ConfigMap
      name: skip-cluster-host
      fieldPath: data.SERVER_HOST
    targets:
      - select:
          kind: IngressRoute
          name: argocd
        fieldPaths:
          - spec.routes.0.match
        options:
          delimiter: "."
          index: 1
