apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../cluster-host
  - configmap.yaml
  - ingressroute.yaml

vars:
  - name: SKIP_SERVER_IP
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: skip-cluster-settings
    fieldref:
      fieldpath: data.SKIP_SERVER_IP

configurations:
  - varreference.yaml
