apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../cluster-host
  - namespace.yaml
  - helmrelease.yaml
  - ingressroute.yaml

replacements:
  - source:
      kind: ConfigMap
      name: skip-cluster-settings
      fieldPath: data.SKIP_BASE_DOMAIN
    targets:
      - select:
          kind: IngressRoute
          name: harbor
        fieldPaths:
          - spec.routes.0.match
          - spec.routes.1.match
          - spec.routes.2.match
          - spec.routes.3.match
          - spec.routes.4.match
        options:
          delimiter: "@@"
          index: 1
      - select:
          kind: HelmChart
          name: harbor
        fieldPaths:
          - spec.valuesContent
        options:
          delimiter: "@@"
          index: 1
