apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../cluster-host
  - namespace.yaml
  - helmrelease.yaml
  - ingressroute.yaml

vars:
  - name: SKIP_BASE_DOMAIN
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: skip-cluster-settings
    fieldref:
      fieldpath: data.SKIP_BASE_DOMAIN

configurations:
  - varreference.yaml
