---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBasutyJwsmWDRkRh9r9GrCe7Scj8A2xtBHTWs69zg+UpN1n3ocnM7kgs3n6rC6BvTJU87k3BsGAkCmuihoCGl0SGUNO2myI0YS/hZAhQxVPNFJUPf8lAJkMWC5xMmksvQey92b/tSZ0W+H2pmE/sbPHwTfuj3gOUGvzKLQrE5l8DVXBIIfsWKzKqOYBQutIW3evsDnK35wdlVbkfJkSZg9cNO+8v3reiN+PrYOhclux+0EGPfPsZwJng0qbb0CrRvN/+0bafhrPS1EIfHGeOvlHI+0hC61aGiWvOdiC8ltTIyDsEuSpFZyGh2MPHtTCIVTUvMewymf+2l9kj0cGTtuTrjI8zVPD93q0cQ8GlhisHmfDVLIm7LJ0CRy2AVGShGKLPan4ExwE3aU+UV6WFmiFZx/HxmDDNcatKhpeWxdLQBMg81Xqs6Kv0cmPfUkke2j9gikYvUcMkpF4PEWAkYCa4ZjWsT0S/n6Urxp30dcRCnZ4otP5XjlHPZ1r/12SklkLIH6pkcu6bppW3zCLCoO7sjYva/24/60UuaNrmJmIDBhNqev8ACdnrnKRCqzAB1tSnUAjPd/Jemrb+y7SA2Xgm6MoE9DHaR+b+FaL11TixhjWgFrK8bzW5DAiaWS7piwfF9HwOdSM9FoGUJHkEAss3yJStowHeW6xEZAxhKAieviReM3JcYEoQDu8Tghub9KEhWjU4plmouFfVlqCp14
    admin-user: AgAfYLKclKUqinmWa9sUTNFWKUXm9As1PSxiGXpoTvviC2X7I9zPUUiOJ3VoO2Zd4HFnbeW+4IDE89lJTLRRqnITJ2CBS/IM5yyeEF+ORi7LsFKyocLsvZ7BXheU7fQx4fKHVnJuWBh3W35fglgJQNIVJROsM2A+JFY2KanGqYWVEtqPqusuq1uIcxwMCCxbncLk2Dzq5jYZVNxgil1Z4DcxfZyWF/G8tag/dKPAwXjJukneV6v8nzclMWs984KnMUY8z0PphehwYnczIzbkvqfR/enMTLx+/M/CU7tlRd6ekOC4SZi0xH7ApbQQSQMP7mT+MhHaXrIrgqevpdd5QfNLEzcVuc02wn0u34Au4rLLgpHMLU58b1QT745jJoWWwzEbz17jzgliIR1up5BlpZRN/f+ZQH/iUw02Lgbx4cXh6UWiMoXQA9geI1xr7tN0sQeU70uKSvzCJx/bKdruThZE3WHtmyaU7142ORpJIW/Ez8ba1pe30cA8I5z3dmE9r9T90jf66+tcQIh3oC6QaVBLSCctHgqyBeYDlkmmsACr79Gn/rnwmPL9vC6/bhRlXhf8DCxberZXyJCNgmQwXkk7Wm3bB2HKwa0kPi5RppeZmua3xPwa9He3LPrRrVHfOwaKvYNqTRgh/DUmJMjBxdXc+cow7FFNwK1R8OdoOoAeDCPpe6NfKrF+Wiq45S4NWM5XAYthuQ==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
